pool:
  vmImage: 'ubuntu-16.04'

steps:
  - bash: |
      IMAGE_NAME=miam-$(Build.BuildId)
      docker build -t ${IMAGE_NAME} -f Dockerfile-CI . 
      docker image rm ${IMAGE_NAME}
    displayName: Run Tests