pool:
  vmImage: 'ubuntu-16.04'

steps:
  - bash: |
      #!/bin/bash

      set -e
      IMAGE_NAME=miam-$(Build.BuildId)
      docker build -t ${IMAGE_NAME} -f Dockerfile-CI . 
      docker run -n ${IMAGE_NAME}-container ${IMAGE_NAME} /bin/ls 
      docker cp ${IMAGE_NAME}-container:/go/src/app/test-report.xml ./test-report.xml
      docker rm ${IMAGE_NAME}-container
      docker image rm ${IMAGE_NAME}
    displayName: Run Tests

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test-*.xml' 
      #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
      #mergeTestResults: false # Optional
      failTaskOnFailedTests: false # Optional
      #testRunTitle: # Optional
      #buildPlatform: # Optional
      #buildConfiguration: # Optional
      #publishRunAttachments: true # Optional