pool:
  vmImage: 'ubuntu-16.04'

steps:
  - bash: |
      #!/bin/bash

      set -e
      IMAGE_NAME=miam-$(Build.BuildId)
      docker build -t ${IMAGE_NAME} -f Dockerfile-CI . 
      docker run --rm ${IMAGE_NAME} go test ./...
      docker image rm ${IMAGE_NAME}
    displayName: Run Tests