FROM golang:1.13

ENV GO111MODULE=on

# RUN apt-get update && \
RUN apt install -y \
        binutils \
        gcc \
        make

WORKDIR /go/src/app
COPY . .

RUN go get -u github.com/jstemmer/go-junit-report

RUN go get -d -v ./...

RUN go test -v ./... 2>&1 | tee go-report
RUN cat go-report | go-junit-report > test-report.xml